global:
  namespace: kyma-integration
  nginx:
    namespace: kyma-system
  istio:
    tls:
      secretName: istio-ingress-certs
    gateway:
      name: kyma-gateway
      namespace: kyma-system
  containerRegistry:
    path: eu.gcr.io/kyma-project
  connector_service:
    version: 0.5.0
  connector_service_tests:
    version: 0.5.0
  event_service:
    version: 0.5.0
  proxy_service:
    version: 0.5.0
  gateway_tests:
    version: 0.5.0
  metadata_service:
    version: 0.5.0
  metadata_service_tests:
    version: 0.5.0
  remote_environment_controller:
    version: 0.5.0
  remote_environment_controller_tests:
    version: 0.5.0
  remote_environment_broker:
    version: 0.5.0
