global:
  namespace: kyma-integration
  nginx:
    namespace: kyma-system
  istio:
    tls:
      secretName: istio-ingress-certs
    gateway:
      name: kyma-gateway
      namespace: kyma-system
  containerRegistry:
    path: eu.gcr.io/kyma-project
  connector_service:
    dir: rc/
    version: 0.5-rc
  connector_service_tests:
    dir: rc/
    version: 0.5-rc
  event_service:
    dir: rc/
    version: 0.5-rc
  proxy_service:
    dir: rc/
    version: 0.5-rc
  gateway_tests:
    dir: rc/
    version: 0.5-rc
  metadata_service:
    dir: rc/
    version: 0.5-rc
  metadata_service_tests:
    dir: rc/
    version: 0.5-rc
  remote_environment_controller:
    dir: rc/
    version: 0.5-rc
  remote_environment_controller_tests:
    dir: rc/
    version: 0.5-rc
  remote_environment_broker:
    dir: rc/
    version: 0.5-rc
