dex:
  tls:
    createSecret: false

service-catalog:
  etcd-stateful:
    replicaCount: 1

minio:
  service:
    type: NodePort

azure-broker:
  enabled: false

global:
  containerRegistry:
    path: eu.gcr.io/kyma-project
  istio:
    gateway:
      name: kyma-gateway
  etcdBackup:
    enabled: false
    secretName: etcd-backup-abs-credentials
  acceptance_tests:
    version: 0.5.0
  alpine_net:
    version: 0.5.0
  api_controller:
    version: 0.5.0
  api_controller_acceptance_tests:
    version: 0.5.0
  apiserver_proxy:
    version: 0.5.0
  binding_usage_controller:
    version: 0.5.0
  configurations_generator:
    version: 0.5.0
  docs:
    version: 0.5.0
  environments:
    version: 0.5.0
  etcd_backup:
    version: 0.5.0
  event_bus:
    version: 0.5.0
  event_bus_tests:
    version: 0.5.0
  helm_broker:
    version: 0.5.0
  kubeless_test_client:
    version: 0.5.0
  test_environments:
    version: 0.5.0
  test_logging_monitoring:
    version: 0.5.0
  ui_api_layer:
    version: 0.5.0
  ui_api_layer_acceptance_tests:
    version: 0.5.0

test:
  acceptance:
    core:
      # environments used in remote-environment acceptance test
      remoteEnvironment:
        disabled: "true"
        brokerNamespace: kyma-integration
        linkingTimeout: 4m
        unlinkingTimeout: 4m
        # Currently Pods with istio sidecar they have a long termination time, because of that we need to have
        # such log timeout for teardown (waiting until namespace will be terminated)
        tearDownTimeoutPerStep: 3m
    ui:
      # tests uses chromium that require more memory
      requests:
        memory: 300Mi
        cpu: 200m
      limits:
        memory: 500Mi
        cpu: 300m
