imageRegistry: "quay.io/coreos"

containerPort: 5556

oidc:
  kymaClient: "kyma-client"
  consoleClientId: console
  consoleClientName: 'Console'
  grafanaClientId: grafana
  grafanaClientName: 'Grafana UI'
  jaegerClientId: jaeger
  jaegerClientName: 'Jaeger UI'

global:
  gateway:
    name: kyma-gateway
  static_users_generator:
    version: 0.5.0
  containerRegistry:
    path: eu.gcr.io/kyma-project
